version: '3'
services:
  mongo:
    container_name: mongo
    image: "mongo"
    networks:
      - digituz
  proxy:
    container_name: digituz-proxy
    build: ./proxy/
    networks:
        - digituz
  gateway:
    container_name: digituz-gateway
    build: ./gateway/
    ports:
      - 80:80
      - 443:443
    networks:
      - digituz
    depends_on:
      - proxy
      - mongo
    volumes:
      - "/etc/letsencrypt/:/etc/letsencrypt"
  auth0-angular-client:
    container_name: auth0
    image: "digituz/auth0-angular-client"
    networks:
      - digituz
    depends_on:
      - gateway

  # brand house images
  projects-api:
    container_name: projects-api
    image: "digituz/rest-flex"
    networks:
      - digituz
    environment:
      - DOMAIN=projects
      - MONGODB_URL=brand-house-db:27017/projects
      - AUTH0_DOMAIN=digituz-corp.auth0.com
      - AUTH0_AUDIENCE=https://projects.digituz.com.br
    depends_on:
      - gateway
  companies-api:
    container_name: companies-api
    image: "digituz/rest-flex"
    networks:
      - digituz
    environment:
      - DOMAIN=companies
      - MONGODB_URL=brand-house-db:27017/companies
      - AUTH0_DOMAIN=digituz-corp.auth0.com
      - AUTH0_AUDIENCE=https://companies.digituz.com.br
    depends_on:
      - gateway
  project-stages-api:
    container_name: project-stages-api
    image: "digituz/rest-flex"
    networks:
      - digituz
    environment:
      - DOMAIN=project-stages
      - MONGODB_URL=brand-house-db:27017/project-stages
      - AUTH0_DOMAIN=digituz-corp.auth0.com
      - AUTH0_AUDIENCE=https://project-stages.digituz.com.br
    depends_on:
      - gateway
  brand-house:
    container_name: brand-house
    image: "digituz/brand-house"
    networks:
      - digituz
    depends_on:
      - projects-api
      - companies-api
      - project-stages-api
networks:
  digituz:
