version: '3'
services:
  mongo:
    container_name: mongo
    image: "mongo"
    networks:
      - digituz
  proxy:
    container_name: digituz-proxy
    build: ./proxy/
    networks:
        - digituz
  gateway:
    container_name: digituz-gateway
    build: ./gateway/
    ports:
      - 80:80
      - 443:443
    networks:
      - digituz
    depends_on:
      - proxy
      - mongo
    volumes:
      - "/etc/letsencrypt/:/etc/letsencrypt"
  auth0-angular-client:
    container_name: auth0
    image: "digituz/auth0-angular-client"
    networks:
      - digituz
    depends_on:
      - gateway
  brand-house-backend:
    container_name: brand-house-backend
    image: "digituz/brand-house-backend"
    networks:
      - digituz
    depends_on:
      - gateway
  brand-house:
    container_name: brand-house
    image: "digituz/brand-house-frontend"
    networks:
      - digituz
    depends_on:
      - brand-house-backend
networks:
  digituz:
